;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                            ;;
;; TurboBasic XL v1.5 disassembly, in MADS format.            ;;
;;                                                            ;;
;; Disassembled and translated to MADS by dmsc, 2017-2021     ;;
;;                                                            ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;
; This disassembly is based on the published TurboBasic XL binaries,
; and should be public-domain by now.
;

ERRTAB
           .cb ' AT LINE '
           .cb '?BLOAD'
           .cb 'MEM'
           .cb 'VALUE'
           .cb '>#VARS'
           .cb '$LEN'
           .cb '?DATA'
           .cb '>32767'
           .cb 'INPUT'
           .cb 'DIM'
           .cb 'STACK'
           .cb 'OVERFLOW'
           .cb '?LINE'
           .cb '?FOR'
           .cb 'TOO LONG'
           .cb '?DEL'
           .cb '?GOSUB'
           .cb 'GARBAGE'
           .cb '?CHR'
           .cb 'MEM'
           .cb '#'
           .cb '?LOAD'
           .cb '?NEST'
           .cb '?WHILE'
           .cb '?REPEAT'
           .cb '?DO'
           .cb '?EXIT'
           .cb 'XPROC'
           .cb '?EXEC'
           .cb '?PROC'
           .cb '?#'
           .cb 'IS OPEN'
           .cb '?DEV'
           .cb 'WR ONLY'
           .cb 'CMD'
           .cb 'NOT OPEN'
           .cb '#'
           .cb 'RD ONLY'
           .cb 'EOF'
           .cb 'TRUNC'
           .cb 'TIMEOUT'
           .cb 'NAK'
           .cb '!FRAME'
           .cb 'CURSOR'
           .cb '!OVERRUN'
           .cb 'CHKSUM'
           .cb 'DONE'
           .cb 'MODE'
           .cb 'NOT IMPL'
           .cb 'RAM'
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb ' '
           .cb 'D?:'
           .cb '>#FILES'
           .cb 'DSK FULL'
           .cb 'FATAL I/O'
           .cb 'FILE#'
           .cb 'NAME'
           .cb 'POINT'
           .cb 'LOCKED'
           .cb 'DCMD'
           .cb '>DIR'
           .cb '?FILE'
           .cb 'POINT'
           .cb '?APPND'
           .cb 'BAD SECTORS'

; vi:syntax=mads
